{{- if not .Values.stackstate.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  service-token: {{ .Values.stackstate.serviceToken | b64enc | quote }}
{{- end }}
